### ISSUE TITLE
New release / update v12 tag

### ISSUE THREAD

**Issue by sschuberth** [DavidAnson/markdownlint-cli2-action#111]
Can we please get a new tag here as well, to bubble up the fix for https://github.com/DavidAnson/markdownlint/issues/945 via `markdownlint-cli2` to here?

**Comment by DavidAnson** [comment]
Soon: https://github.com/DavidAnson/markdownlint/blob/main/doc/ReleaseProcess.md

**Comment by DavidAnson** [comment]
v13 is now available.
