### ISSUE TITLE
Node16 deprecated

### ISSUE THREAD

**Issue by damacus** [DavidAnson/markdownlint-cli2-action#117]
thanks for the ace action. 

Can we update the node runtime to node20?

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: DavidAnson/markdownlint-cli2-action@v13
```

**Comment by DavidAnson** [comment]
I've tried to do this a couple of times, but Node 16 was all they supported. It looks like Node 20 is what they support now, so I will update this for the next version.

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions
