### ISSUE TITLE
Add option to only lint changed files

### ISSUE THREAD

**Issue by Pandapip1** [DavidAnson/markdownlint-cli2-action#12]
This massively reduces runtime when you have [a repository with half a thousand markdown files](https://github.com/ethereum/EIPs) and/or cannot retroactively lint existing invalid markdown files.

Changed files can be determined as follows:

```js
const fetched = await octokit.paginate(octokit.rest.pulls.listFiles, {
    owner: pull_request?.base.repo.owner.login,
    repo: pull_request?.base.repo.name,
    pull_number: pull_request?.number as number,
});
```

**Comment by DavidAnson** [comment]
If you want to exclude files/paths from linting, that is already supported.

How long does a full linting pass take? Can you link to one of the runs?

**Comment by Pandapip1** [comment]
As it turns out, it doesn't take too long (about 10 seconds). The problem is that due to the way the repository works, one can't just update all the files to use the new format, and so the linter should *only* care about the files that were changed, otherwise the CI would always fail with about 1.5k violations.

**Comment by wolf99** [comment]
Saw this in the change notes of the action and realised there may be an issue with this approach.

As the version of this action (and indeed many other actions) change, new functionality is added and old functionality is improved.
This means that even files that were already linted, may now show new issues, i.e. newly found issues in existing files.
When you are scanning all files, such issues will show up every time a workflow runs. 
But applying linting only on changed files means that those files never be linted again (unless subsequently altered of course) so will only be linted up to the version of this action which ran on them.

Which means that the lint status of even new files can gradually degrade over time.

**Comment by Pandapip1** [comment]
This is intentional, as in our case we prefer degradation over time to forced updates.
