### ISSUE TITLE
Support the installation of custom rules

### ISSUE THREAD

**Issue by sschuberth** [DavidAnson/markdownlint-cli2-action#134]
We'd like to use `markdownlint-rule-max-one-sentence-per-line` with this action, but there seems to be no option to install custom rules, so we needed to revert to running `markdownlint-cli2` directly. Any chance for supporting custom rules?

**Comment by DavidAnson** [comment]
I do not think this is possible within the GitHub Actions framework. This paragraph - and especially the second sentence - seem to say that dependencies cannot be added dynamically: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

**Comment by DavidAnson** [comment]
Closing as this seems to be explicitly not supported by GitHub Actions. (It's not clear if a package manager is even available to Actions.)
