### ISSUE TITLE
Single value glob fails

### ISSUE THREAD

**Issue by wolf99** [DavidAnson/markdownlint-cli2-action#4]
The following, taken from the example in the README, fails when used in a GitHub workflow:

```yaml
    glob: **/*.md
```
See: https://github.com/exercism/problem-specifications/actions/runs/1569735446/workflow

Instead the following is required

```yaml
    glob: |
      **/*.md
```

Which works: https://github.com/exercism/problem-specifications/runs/4498374968?check_suite_focus=true

Could either the README, or the implementation be updated?

**Comment by DavidAnson** [comment]
Sorry about that! The implementation is fine, the example happens to be a YAML syntax error because of the leading "*". Quoting that string should allow it to be used on a single line - or you can move to the multi line syntax as you demonstrate. I will update the documentation.

**Comment by DavidAnson** [comment]
Specifically, this should work: `glob: "**/*.md"`

**Comment by wolf99** [comment]
Ah I did wonder about trying quotes. My editor seemed to think it was OK locally, but I didn't want to rely on something that wasn't reflected in the docs.

Thanks for clarifying!
