### ISSUE TITLE
[Feature Request] Annotations

### ISSUE THREAD

**Issue by Stanzilla** [DavidAnson/markdownlint-cli2-action#5]
Hey there, only today learned that you have an official GitHub action, have been using a npm script for now.

Are there any plans to add support for annotations?

**Comment by DavidAnson** [comment]
That does not seen to be supported for Actions yet: https://github.community/t/what-are-annotations/16173

**Comment by DavidAnson** [comment]
Hold the phone, this may be supported now: https://github.com/actions/toolkit/tree/main/packages/core#annotations

**Comment by Stanzilla** [comment]
Hah yea, here's an example implementation a different linter action: https://github.com/nebularg/actions-luacheck/commit/44fc6995d2fc7885e4aa77a60f81ba7503ad43a7

**Comment by DavidAnson** [comment]
[FYI, this won't show up until I publish to the Marketplace later today]

**Comment by Stanzilla** [comment]
Awesome, thank you!

**Comment by DavidAnson** [comment]
This is a little awkward to test, but here's a preview: https://github.com/DavidAnson/markdownlint-cli2-action/pull/6/files

(I'm pretty sure the duplicates are due to how I'm testing this.)

**Comment by DavidAnson** [comment]
It should be available now, either via the existing `v5` tag or the new `v5.1.0` tag.
