### ISSUE TITLE
Linter doesn't recognize more than one changed file

### ISSUE THREAD

**Issue by techwritermat** [DavidAnson/markdownlint-cli2-action#58]
I tried your workflow to lint changed files only (I literally used what was in changed.yml in your repo) and I've run into an issue where, if there is more than one file, the linter doesn't work. 

It seems to have to do with the fact that the separator "/n" gets URL-encoded (see https://github.com/tj-actions/changed-files#known-limitation) and the result is not a newline-separated list of files but a single, long string of filenames that your action doesn't recognize, e.g.: `docs/folder/item1.md%0Adocs/folder/item2.mdx%0Adocs/folder/item3.md`.

The 'changed-files' action may save the result in JSON form. Perhaps if markdownlint-cli2-action accepted JSON instead of a newline-separated list, this would work.

**Comment by DavidAnson** [comment]
This is a limitation tj-actions/changed-files, GitHub Actions, and the sample. You are welcome to use a different mechanism to provide input. From what I've seen, the best practice for providing a list of files (which may contain spaces) in an Action is to use a newline-delimited list as is done here. Unfortunately, it seems the changed-files action is not capable of doing so easily. The JSON output it offers appears to be custom/non-standard.

I will look at improving the sample. If you know of a better standard for passing files in Actions, please let me know! Thanks.

**Comment by DavidAnson** [comment]
I could allow the separator to be configurable. Newline seems the correct default, but this would allow better interoperability.
