### ISSUE TITLE
Not detecting README.md

### ISSUE THREAD

**Issue by wolf99** [DavidAnson/markdownlint-cli2-action#68]
Hi David,

Happy new year!

I am working to add this action to Googles OSV scanner repo on this PR: https://github.com/google/osv-scanner/pull/129

I have run into two small problems there. The main one is that the action does not seem to be noticing the README.md that is in the repo's root. I have configured the glob as `"**/*.md"` which I thought should cover all markdown files.
I have set the workflow in this file in the dff: https://github.com/google/osv-scanner/pull/129/files#diff-89a1744df6121f5440951ae1c391b3557e249cf7dd1cd735f81ba4df337bf0ca 
Can you check if I've done something boneheaded?

Second smaller item is that I am not clear how to pass configuration within in the workflow YAML file. I would like to configure MD013, without resorting to using a configuration file for one configuration, if possible.
Could you point out where I would see an example in the docs maybe?

Thank you!

**Comment by DavidAnson** [comment]
That syntax looks correct to me. What makes you think it is not including README when it runs?

Configuration of the CLI2 tools is always done by file. You won't be able to embed that in the workflow YAML.

**Comment by wolf99** [comment]
Ah I had changed the globs.

Beforehand it was :

```yaml
          globs: |
            "**/*.md"
```

And the action reported 

```console
Linting: 0 file(s)
Summary: 0 error(s
````

https://github.com/google/osv-scanner/actions/runs/3877518396/jobs/6612625620

When I changed the globs to 

```yaml
          globs: "**/*.md"
```

Then the action finds the files:
https://github.com/google/osv-scanner/actions/runs/3877550093/jobs/6612690469

This "fixes" the issue for me. However it seems like a bug because the semantics for both ways of specifying the glob should be the same, right?

(either a single string or a list of strings with one item, it's all the same)

**Comment by DavidAnson** [comment]
I agree with your sentiment, but that is YAML behavior, not something I control. In the single-line case, I believe quotes are necessary, because of the asterisk and get removed by the parser. In the multi-line case, they do not get removed.
