### ISSUE TITLE
Support .markdownlintignore

### ISSUE THREAD

**Issue by rubensa** [DavidAnson/markdownlint-cli2-action#77]
So I can use same ignore patterns when using https://github.com/marketplace/actions/markdownlint-cli2-action and  https://github.com/DavidAnson/vscode-markdownlint without having to write the same rules twice.

**Comment by DavidAnson** [comment]
`.markdownlintignore` is kind of a legacy file. What you want is possible today with `.markdownlint-cli2.jsonc`. Would you be able to convert to that instead?
