### ISSUE TITLE
Feature request: link to the issue reference in the comment

### ISSUE THREAD

**Issue by atkinsonm** [DavidAnson/markdownlint-cli2-action#79]
As a user of the markdownlint-cli2-action, I would like the inline comments of the actions to hyperlink to the relevant documentation e.g. https://github.com/DavidAnson/markdownlint/blob/main/doc/md034.md so I can quickly reference the rational for an issue and how to fix it.

**Comment by DavidAnson** [comment]
It's a reasonable request, but I don't think it's quite possible today the way you have in mind. Those are called annotations, and they are published via this API: <https://github.com/actions/toolkit/tree/main/packages/core#annotations>. As you can see if you scroll down a bit, there is no option to pass a link for more information.

Best effort, I could append the URL to the end of the text field, where I suppose you could copy and paste it. Or maybe we will get lucky and they will auto detect that link and make it clickable in the report. 

I will have a look at this during the next round of updates.

**Comment by atkinsonm** [comment]
I tried this out today and it is working, at least the basic version. Thank you!
