### ISSUE TITLE
Add option to disable rules

### ISSUE THREAD

**Issue by gr2m** [DavidAnson/markdownlint-cli2-action#86]
Hi there, thank you for the great action 💐 I just learned about it through an internal @github presentation on README/Markdown accessibility

Would it be possible to add an option to the action that would allow to disable one or multiple of [the `MDXXX` rules](https://github.com/DavidAnson/markdownlint#rules--aliases), without the need to use `command: config` and an extra configuration file? I try to keep config files in repositories to a minimum.

If you would be open to that addition, I'd be happy to try to contribute it. I'd appreciate any pointers on how you would implement it

**Comment by DavidAnson** [comment]
You do not need to use the command option if you put the configuration file in the root of the project. But the philosophy of this tool is to configure via file, so I am not looking to make the change you propose. (More info: https://dlaa.me/blog/post/markdownlintcli2) markdownlint-cli supports what you want, so maybe you want to consider that option.

**Comment by gr2m** [comment]
okay, cheers!
