### ISSUE TITLE
Question: Does ** globbing include the current directory?

### ISSUE THREAD

**Issue by wolf99** [DavidAnson/markdownlint-cli2-action#9]
Hi there,

I'm a little confused on the rules for globbing.

I'd like to lint the current directory and subdirectories.

Does `globs: "**/*.md"` specifically cover the current directory as well as subdirectories?

Thanks!

**Comment by DavidAnson** [comment]
Yes, this is what's used by the example that lints all Markdown files in the project.

**Comment by wolf99** [comment]
Thanks @DavidAnson !
