### ISSUE TITLE
Specifying markdownlint-cli2 version as input

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [DavidAnson/markdownlint-cli2-action#94]
At the moment, it seems the `markdownlint-cli2` version is [picked by `npm`](At the moment, it seems the `yamllint` version is [picked by `pip`](https://github.com/ibiqlik/action-yamllint/blob/master/Dockerfile#L4) (`0.8.1`).

Would you find is acceptable to add an input such as `version` to the action's arguments so we could make sure CI is as predictable as possible (?)

I could try and pull request for it, if the answer is "Yes."

Thanks.

**Comment by DavidAnson** [comment]
Each tagged release of the action is bound to a specific version of `markdownlint-cli2` (as well as every other dependency). The bundle `dist/index.js` in the repo is used per GitHub Action guidance.

**Comment by paulo-ferraz-oliveira** [comment]
Got it. Our main use case, though, is to be able to pinpoint a specific version we test the MDs against, off CI.

So, locally you'd have e.g.

```
markdownlint = 0.8.1
```

and that version would later be injected into CI. This eases our searching for references.

At the same time we're using e.g. `@v10` (which is a moving target). Not only can we not easily relate it to `0.8.1` but also, if we're to want all versions in that "branch" (e.g. an action fix in itself - which would "self-update" our CI on the next run) and not move the underlying `0.8.1` further that would also be achievable via a `version` parameter.

👍 

Btw, thanks for the action and the underlying tool. It's been really helpful in spotting issues (both locally and in CI 😄).

**Comment by DavidAnson** [comment]
The implementation of this action is tied to that of the CLI. There is no attempt to make it backward compatible nor forward compatible. What I suggest for your scenario is not using this action and instead invoking the CLI directly from within your own workflow via `run`. That will let you control the version directly and match it with whatever other processes you have.

**Comment by DavidAnson** [comment]
As an aside, because the action is pre-compiled and self-contained, it would seemingly have to contain all past and future versions of the CLI in order to allow choosing at run-time.

**Comment by paulo-ferraz-oliveira** [comment]
> The implementation of this action is tied to that of the CLI. There is no attempt to make it backward compatible nor forward compatible.

And none would be expected 👍 It'd be up to the consumer to make sure they make the right choices.

> What I suggest for your scenario is not using this action and instead invoking the CLI directly from within your own workflow via `run`.

You mean something like installing it via `package.json` and then `npm run`ning it? (this is not being used in a Node.js context, by the way, which means it might work in "regular" GitHub, but maybe not hosted runner (?)).

> As an aside, because the action is pre-compiled and self-contained, it would seemingly have to contain all past and future versions of the CLI in order to allow choosing at run-time.

Yeah, this is good enough reason to not want it 👍

I'll close this. Thanks for the guidance.

**Comment by DavidAnson** [comment]
Yes, you understood my suggestion correctly. Another option is to use the Docker container image for CLI2 if you are worried that your runner machine may not have Node.js installed.
